### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Quu1337** [ldtteam/DynView#1]
Hey,

Could  you add something like target-tps setting? Anything over 15tps is still very playable, keeping 20tps is bit overkill IMO, if the view distance drops to 5 (or whatever is set to minimum) after 3 players join.

This is very low importance to me, but would be very good thing to have. Probably setting minimum view distance to larger would have same effect, or figuring out proper average tick time for settings.

**Comment by someaddons** [comment]
it already exists, the average tick time in the config allows you to determine the target tps. 
Tick time = <50 ms = 20 TPS, Tick time = 100 -> 10 TPS, tick time = 200 -> 5 TPS.

1sec = 1000miliseconds = 1000/X = tps

**Comment by Quu1337** [comment]
Ah damn, neat. Thanks for explaining it very clearly.
Could this info maybe be put on curseforge page or in the configs? Would help stupid people like me.

**Comment by someaddons** [comment]
ye I'll make a spoiler for it, good idea
