### ISSUE TITLE
Compatibility question for Cubic Chunks [Suggestion]

### ISSUE THREAD

**Issue by border999** [ldtteam/DynView#11]
do you also intend to add support for Cubic Chunks vertical chunk render distance?

**Comment by border999** [comment]
though this would mean updating the 1.12.2 version.

**Comment by ravenbuilder934** [comment]
No updates for 1.12, it's not supported any more

**Comment by someaddons** [comment]
no^^

**Comment by border999** [comment]
sad

**Comment by border999** [comment]
when Cubic Chunks comes to 1.16, will you add support?

**Comment by someaddons** [comment]
unlikely, its just an edge-case

**Comment by Raycoms** [comment]
Generally speaking, it works relatively well with cubic chunks, but some things cause issues if you're not careful. Our project is fully open source, so if anyone wants to add a compatibility layer, we invite them to.

**Comment by border999** [comment]
correction, 1.17
