### ISSUE TITLE
Lazy Chunk loading error

### ISSUE THREAD

**Issue by zookeper** [ldtteam/DynView#20]
Some feature set by default in the 1.8.9 ATM 6 pack is causing issues with entity rendering specifically magma cube (for me) in single player mod dynviewdist-2.0

The default minimum rendering is set to 1, however in (the other) magma cube spawns cause the server to permanently hang if the magma cube is spawned and the chunk rendering suddenly lowers...

This is not just with magma cubes, every ones computer has a different capability and when I was searching online what might cause entity rendering crashes it's strictly due to chunks loading and unloading while mobs spawn inside them..

I have increased the minimum range to 9 because that is the minimum requirement for magma cube spawner's which are dedicated to the other and is in fact the largest minimum chunk range in the game so it may be a quick resolution to change the default distance specifically to 9 rather than the multiple threads on reddit that seem to find no resolution for their entity rendering crashes

I must note there is no crash log that specified what exactly was causing the crash only that there is an entity rendering issue and my world went down in the nether and indeed the chunk distance if set to a minimum of 1 would lower it self less than 9 resulting in a crash every time a magma cube spawned and a chunk was unloaded due to "server stress" 

I have had to delete my world and restart from a backup.

No amount of joining the world would let me play it loaded into a server hang every time...

I have changed the minimum distance to 9 and am exploring the other again with zero crashes and lag issues.

I assume that a better resolution would be to change the magma cubes chunk rendering distance however I am unsure if it's a vanilla feature or if it is a mod that is changing it.

But to help the countless other people experiencing this issue it might be wise to suggest to increase the minimum distance of their worlds or it may result in a server hang due to entity rendering issues. Or just change the default of minimum chunk loading distance in the config to 9.

**Comment by someaddons** [comment]
dynamic view has nothing to do with entity rendering, nor does it unload chunks
