### ISSUE TITLE
[suggestion] add Simulated chunks support

### ISSUE THREAD

**Issue by Ki-Tan2934** [ldtteam/DynView#21]
Are there plans to add simulated chunks limited tied to view to this mod?
Settings could be % based to set in stone for example... 50%
20, 18, 16, 14, 12, 10 Render
10, 9, 8, 7, 6, 5, 4 Simulated

Or set numbers
[20-15], [10-14], [8-9], [4-7] Render
[10], [7], [5], [4] Simulated

**Comment by someaddons** [comment]
added in 2.4
