### ISSUE TITLE
[Config Feature Request] Chunk change amount

### ISSUE THREAD

**Issue by Erosion139** [ldtteam/DynView#22]
(1.12.2) When dealing with larger render distances the algorithm is going to be more sluggish to bring the chunks down to a sustainable level if something ends up loading the system a lot (like a new player joining) therefore I think it would be nice to have a way to specify how many chunks the mod jumps when it does its scheduled check. I also can't seem to make its check rate lower than 30 seconds either because my server is loaded or something is wrong with the mod. So I think with the slower check rates a larger distance change would be beneficial although perhaps not as granular.

**Comment by someaddons** [comment]
The idea is that you stabilize at a value the server is running well over time, to not constantly jump around causing unloading and reloading all the time when there is some momentarily lag. The interval is adjustable in the config, you may need to turn off the server before changing it. I won't be updating 1.12 though, I've got no time to maintain super old versions
