### ISSUE TITLE
[Suggestion] MinLag and Max lag trigger for view distance change

### ISSUE THREAD

**Issue by Speiger** [ldtteam/DynView#28]
o/ tried using your mod and dropped it the moment i noticed it uses the same lag value for deciding if it should grow or shrink the radius.

One massive change should be to allow defining the range to grow or shrink the view distance.

I would have set the config for my self:

grow if the lag is below 20ms, and shrink if it is above 35ms, that way if you are in between you just keep the current setting.
That allows you to not force max performance lag on your server but to actually have a good view change as needed.

**Comment by someaddons** [comment]
I think that is too complex for the average end-user since that would require them to have a decent understanding of lag dynamics to choose good values for their results. I think it works just fine as is, averaging on values which get the server to the desired ms ticks.

**Comment by Speiger** [comment]
Right this is to complext:

#Sets the Minimum Lag the server should have to increase the view distance of the server.
"minLag" = 5

#Sets the Maximum lag the server should have to decrease the view distance of the server
"maxLag" = 40

Are you serious? This is like a "MinMax thing"

And if it is to complex have 4 config entries.
1 to decide which system to use. (defaults to old)
1 to use the old system
2 to do the min max thing...

**Comment by Speiger** [comment]
@someaddons ok i want to append to this why this issue was created in the first place.

Dynamic View Distance mod basically forces with the way it is set right now to either have your world in the tiniest render distance or in the highest render distance at any given time. There is no room between this.

And the room for jumping up and down isn't really that big. What if the lag difference between 1 distance is like large enough to be larger then your required difference then it keeps constantly jumping up and down.

The idea between a min max lag is to allow server hosters to configure this tool to only do changes if they are needed.
Because they want to for example only increase the view distance if the server is like not even lagged out at all, while the server should shrink the view distance if it is lagging badly or getting so close to lagging that it is not worth keeping a larger view distance.

With this mod this is not possible. You can only say: MAX LAG or MIN VIEW. There is no freedom to decide how you want your server to perform. And rather set it to a average where you feel the setting is running the server smoothly.

The example if provided with the minLag => 5 and maxLag => 40 is the perfect example for such a thing.
It only increases the view distance if there is enough room to breath, and only decreases it if there is really a need for it.

The way it is now the mod is now. It is basically a gamble. Either it works (while spamming into chat) or it doesn't where it flies out because it doesn't help with the core issue.

Also I am sorry for my second rude comment. You had me at the right point where I was basically stressed out enough and then receiving a answer that I received as dodging because there was no interest or lazyness or whatever you want call it and this basically pulled a trigger for me.

But yeah, I would suggest you to give this another thought. Because at some point, someone like me, who likes to spite other people, might show up and make something that does the exact same as yours, just better and either forcing you indirectly to improve said mod, or getting your mod made irrelevant. 

Luckly, this isn't going to be me because I have already enough projects on my hand, even if this would be a easy snipe to do so. Far easier then ChunkPregenerator xD
