### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by P-rox-y** [ldtteam/DynView#3]
Hey there,

Stopping by to drop off this log; can't seem to figure out what's causing the exception. 

I'm guessing DynView doesn't play nice with OptiFine at times

[crash-2020-04-19_14.26.19-server.txt](https://github.com/ldtteam/DynView/files/4500025/crash-2020-04-19_14.26.19-server.txt)

**Comment by someaddons** [comment]
yes optifine is coremodding the vanilla class, causing it issues, report to them

**Comment by someaddons** [comment]
btw you should not put client side mods like optifine on your server
