### ISSUE TITLE
Void trading not working even with chunkunload set to false

### ISSUE THREAD

**Issue by MickZi** [ldtteam/DynView#30]
The Void Villager Trading concepts requires the chunks to be unloaded after the player moves trough the portal. After installing the mod void trading stops working by default, one would expect if you change "chunkunload" to false this mechanic would disable.

My config:
```
{
  "minChunkViewDist": {
    "desc:": "The minimum chunk view distance allowed to use. Default: 5, minimum 3, maximum 200",
    "minChunkViewDist": 10
  },
  "maxChunkViewDist": {
    "desc:": "The maximum chunk view distance allowed to use. Set to the max a player could benefit from. Default: 15, minimum 1, maximum 200",
    "maxChunkViewDist": 20
  },
  "meanAvgTickTime": {
    "desc:": "The average tick time to stabilize the chunk view distance around. Setting it higher than 50ms is not advised, as after 50ms the TPS will go below 20. Default: 45ms, min: 10, max:100",
    "meanAvgTickTime": 20
  },
  "viewDistanceUpdateRate": {
    "desc:": "The update frequency of average server tick time checks to update view distances.(In seconds) Default: 30, min:1, max:1000",
    "viewDistanceUpdateRate": 30
  },
  "minSimulationDist": {
    "desc:": "The minimum simulation distance allowed to use. Default: 4, minimum 1, maximum 200",
    "minSimulationDist": 10
  },
  "maxSimulationDist": {
    "desc:": "The maximum simulation distance allowed to use. Default: 10, minimum 1, maximum 200",
    "maxSimulationDist": 10
  },
  "adjustSimulationDistance": {
    "desc:": "Enables automatic simulation distance adjustment. Default: true",
    "adjustSimulationDistance": false
  },
  "logMessages": {
    "desc:": "Whether to output log messages for actions done. This can be helpful to balance the other settings nicely. Default \u003d true",
    "logMessages": true
  },
  "chunkunload": {
    "desc:": "Enable slow chunk unloading(~1minute) after load, helps with mods hot-loading chunks frequently. Default: true",
    "chunkunload": false
  }
}
```

**Comment by someaddons** [comment]
chunkunload only slows down the unloading, it does not trigger nor prevent it. This mod does not alter chunkloading techniques, it just alters the distance around the player in which stuff loads

**Comment by MickZi** [comment]
Chunkunload is causing the chunks to take longer to unload even when set to false, that can't be intended behavior right?

**Comment by someaddons** [comment]
mod/minecraft version?

**Comment by MickZi** [comment]
MC 1.18.2
Fabric 0.13.3
Dynview-1.18.1-2.6

List of other mods
![image](https://user-images.githubusercontent.com/78419926/159983094-41b81c4f-acea-432f-85bb-83a4534a369b.png)

**Comment by someaddons** [comment]
ah in fabric the config isnt implemented/has no effect

**Comment by MickZi** [comment]
Ah that's unfortunate, are you looking into implementing this in the future? We would love to use this mod but sacrificing the trading hall for it isn't an option for us :/

**Comment by someaddons** [comment]
I'll probably fix it sometime ye, though not a fan of abusive villager-bug-slave playstyles
