### ISSUE TITLE
[Crash][Quilt 1.18.2] Server tick loop

### ISSUE THREAD

**Issue by faeldray** [ldtteam/DynView#35]
We're having an issue on our server where in an attempt to reduce lag, I added several serverside mods including this one. And it worked fine when I was logged in, but as soon as another player logged in (whether she was the only one connected or not), the server would crash. I was able to isolate it to Dynamic View; if I remove it from the server, she can log in just fine.

[Crash report and latest.log](https://gist.github.com/faeldray/56d5fda4d12364502c6e97118aa19dfe)

**Comment by someaddons** [comment]
quilt isnt supported
