### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by tobi-polar** [ldtteam/DynView#5]
I have an occasional crash on my server. Seems to mention DynView and Performant although I have no idea what the issue is, is it a compatibility issue between the two?

Minecraft:1.15.2
Forge: 31.2.27
DynView: dynviewdist-1.5
https://pastebin.com/GbBXsMDe

**Comment by someaddons** [comment]
for some weird reason the internal minecraft function crashes when called normally by dynamic view, performant has no effect on this. I'm not sure why this happens, and the servers I know have been running both without this issue, so I kinda do suspect it beeing some mod compat issue although its hard to tell which would cause it. Maybe if you can get a way to reliably reproduce it it becomes easier to find

**Comment by tobi-polar** [comment]
Still having this issue.. 
Here's my config as well, changed it to .txt so I could share it here. Does the view distance in server.properties have any effect on this? in server.properties view distance is 10
[dynview-common.txt](https://github.com/ldtteam/DynView/files/4922926/dynview-common.txt)

**Comment by someaddons** [comment]
view distance in the server properties is ignored/has no effect. Like I said if you find which mod causes this issue I may be able to fix it, but I'm not able to reproduce it at all, nor do any of the servers I got access on ever had such a crash.
