### ISSUE TITLE
Mark mod as serverside only

### ISSUE THREAD

**Issue by phit** [ldtteam/DynView#8]
Please mark the mod as server only via
https://mcforge.readthedocs.io/en/latest/concepts/sides/#writing-one-sided-mods

right now it will cause a red X in the server list if the mod is missing on the client, thanks!

**Comment by Vaelzan** [comment]
This is still an issue months later. Any chance it could get looked at?

**Comment by someaddons** [comment]
bleh I had fixed it, seems forge did change it again

**Comment by Vaelzan** [comment]
Thanks, Tarina!

**Comment by ChronosWS** [comment]
This seems to be happening again?  Also with Limited Chunks.  

`09:10:08] [Netty Client IO #7/INFO]: Server has additional mods that may be needed on the client: dynview@ANY, limitedchunks@`
